### ISSUE TITLE
Cause eclipse freeze

### ISSUE THREAD

**Issue by Tony-Proum** [angelozerr/eclipse-wtp-webresources#20]
The plugin cause eclipse freeze or being really slow when editing html files.
The memory usage is unstable when eclipse became slowly

**Comment by angelozerr** [comment]
@Tony-Proum have you a problem again? Can I close this issue?

**Comment by Tony-Proum** [comment]
I had do a quick test, and everything seems Ok. No freeze, with the default configuration.
You can close this issue

**Comment by angelozerr** [comment]
Thanks @Tony-Proum for having tested. Great news.

**Comment by danielsokolowski** [comment]
Hello there, may I recommend to adjust the setting to always search all CSS with a suboption '- if no link element found'. 

Reason I am asking is that my link tags use server side functionality which resolve to the proper location when deployed but are useless when developing. 

```
<link rel="stylesheet" type="text/css" href="{!URLFOR($Resource.ocms_mli_pageSupport, 'css/ocms-reset+support-v2-edit-template.css')}" />
```
