### ISSUE TITLE
Skip validation when embedded PHP script is used

### ISSUE THREAD

**Issue by kaloyan-raev** [angelozerr/eclipse-wtp-webresources#32]
Consider the following snippet: 
``` HTML
<img src="<?php echo $picture_path ?>">
```
In this case the src value is marked as error by the validator. This is not useful and actually annoying for users. Since the output of the PHP script cannot be determined during design time, it would be better to skip the validation when we have embedded PHP script in the src value.

**Comment by angelozerr** [comment]
It was the same problem with JSP scriptlet. For that @gamerson have implemented an extension point to ignore validation. See JSPScriptletIgnoreValidator declared https://github.com/angelozerr/eclipse-wtp-webresources/blob/master/org.eclipse.a.wst.html.webresources.core/plugin.xml#L79

For PHP we should have a new extension point declaration like PHPIgnoreValidator

**Comment by kaloyan-raev** [comment]
Thanks for the hint! See PR https://github.com/angelozerr/eclipse-wtp-webresources/pull/33
