### ISSUE TITLE
Undefined JavaScript/Css file

### ISSUE THREAD

**Issue by Ghassan-Fadila** [angelozerr/eclipse-wtp-webresources#38]
Hello,

When trying to load a file without specify the protocol the editor shows this error (in the title):

for example:

```html
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.20/angular.min.js"></script>
```

or 

```html
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
```

adding https or http solve this, but is should work without it,

Thanks a lot,
Ghassan

**Comment by angelozerr** [comment]
Today WTP WebResources ignore validation for script/link which starts with http. 

To fix this issue, I suppose that I must add rule which urll which starts with //

I would like to provide to give a preference to check the existing of the url which start with http and //

**Comment by angelozerr** [comment]
I have fixed the problem and you can validate if you wish extrenal URL. See https://github.com/angelozerr/eclipse-wtp-webresources/wiki/WebResourcesPreferences#external-url
