### ISSUE TITLE
Data URI schemes should not be marked as errors

### ISSUE THREAD

**Issue by kaloyan-raev** [angelozerr/eclipse-wtp-webresources#42]
Data URI schemes are described here: http://en.wikipedia.org/wiki/Data_URI_scheme

The following html fragment is a valid representation of a "red dot" image:

``` html
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUA
AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO
9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="Red dot" />
```

But EWW marks it with "Undefined Image file" error.

**Comment by angelozerr** [comment]
It should be cool if hover could display the image too.

**Comment by staabm** [comment]
I could also think about a QuickFix which inlines a image which was previously referenced by path, so the webtools would generate the corresponding inline html and replaces the former path with it.

**Comment by kaloyan-raev** [comment]
@angelozerr Thanks!

**Comment by angelozerr** [comment]
@kaloyan-raev you are welcome. See https://github.com/angelozerr/eclipse-wtp-webresources/wiki/Image-Features#data-uri-scheme to see screenshot for hover

**Comment by kaloyan-raev** [comment]
@angelozerr I've already seen it live in my IDE :-)
