### ISSUE TITLE
Avoid validating class values with PHP code inside

### ISSUE THREAD

**Issue by kaloyan-raev** [angelozerr/eclipse-wtp-webresources#43]
In the following HTML fragment the class valued is marked with an "Undefined CSS class" warning:

``` html
<span class="<?=$class_name?>">Text</span>
```

This is not very helpful, because the validator does not actually evaluate the PHP code. Therefore, it's better to skip the validation for values with PHP code inside.

**Comment by angelozerr** [comment]
https://github.com/angelozerr/eclipse-wtp-webresources/blob/master/org.eclipse.a.wst.html.webresources.core/src/org/eclipse/wst/html/webresources/internal/core/validation/PHPScriptIgnoreValidator.java should be improved. 

Any contribution are welcome!

**Comment by kaloyan-raev** [comment]
It seems the ignore validator a registered only for a fixed set of tags like IMG, A, SCRIPT. Here, I believe, we should be able to ignore the class attribute for any tag.

**Comment by angelozerr** [comment]
@kaloyan-raev I will see that. Could you just check that PHPScriptIgnoreValidator.java  ignore too "<?"

If no could you create a PR please for that.

**Comment by angelozerr** [comment]
Now the ignore validator is called for class attribute. 

@kaloyan-raev I have fixed this problem with JSP, plse do the same thing with PHP. Thanks.

**Comment by kaloyan-raev** [comment]
@angelozerr Thanks! I created PR #45.
