### ISSUE TITLE
Unable to disable validation

### ISSUE THREAD

**Issue by mniewrzal** [angelozerr/eclipse-wtp-webresources#44]
Unable to disable validation with Validation preference page. For example such snippet:
```html
<html><body>
	<div class="someclass"></div>
</body></html>
```
will produce "Undefined CSS class" warning. There is no way to disable it because even if "Web Resources Validator" will be disabled (manual and build) warning message is still visible.

**Comment by angelozerr** [comment]
I think problem comes from when you are typing in the editor. I have fixed this problem with the attached patch.

Please retry and tell me if it's OK. Thanks

**Comment by mniewrzal** [comment]
Yes, now css validation is disabled when "Web Resources Validator" is disabled. Thanks:)

**Comment by angelozerr** [comment]
That's cool, thanks @mniewrzal to have tested.

I close the issue.
